var mongoose = require('mongoose')
    , Schema = mongoose.Schema;

var bunchSchema = new Schema({
    bunch_id: String, //Generated by direction and incrementing value
    begin: Date,
    end: Date,
    bus_enter: [{bus: { type: Schema.Types.ObjectId, ref: 'Trip' }, time: Date}],
    bus_exit: [{bus:{ type: Schema.Types.ObjectId, ref: 'Trip' }, time: Date}],
    locations: [{ time: Date, coordinates: [Number] }], //distances?
    traffic: [{ time: Date, speed: Number }]
}, {timestamps: true});

module.exports = mongoose.model('Bunch', bunchSchema);