var mongoose = require('mongoose')
    , Schema = mongoose.Schema;

var tripSchema = new Schema({
    trip_id: String, //generated by VehicleRef + start Date
    vehicleref: String,
    begin: Date,
    end: Date,
    destination: String,
    stops: [{ time: Date, stop: String }],
    active: Boolean,
    termination_reason: String,
    bunch_data: [{ time: Date, speed: Number, coordinates: [Number] }],
    bunch_time: Number,
    waiting: [{ value: Boolean, time: Date }],
}, { timestamps: true });

module.exports = mongoose.model('Trip', tripSchema);